# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

heat_template_version: 2013-05-23

description: >
  Clearwater Ellis node

parameters:
  public_mgmt_net_id:
    type: string
    description: ID of public management network
    constraints:
      - custom_constraint: neutron.network
        description: Must be a valid network ID
  private_mgmt_net_id:
    type: string
    description: ID of private management network
    constraints:
      - custom_constraint: neutron.network
        description: Must be a valid network ID
  flavor:
    type: string
    description: Flavor to use
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a valid flavor name
  image:
    type: string
    description: Name of image to use
    constraints:
      - custom_constraint: glance.image
        description: Must be a valid image name
  key_name:
    type: string
    description: Name of keypair to assign
    constraints:
      - custom_constraint: nova.keypair
        description: Must be a valid keypair name
  base_mgmt_security_group:
    type: string
    description: ID of base security group for all Clearwater nodes (management)
  ellis_mgmt_security_group:
    type: string
    description: ID of security group for Ellis nodes (management)
  repo_url:
    type: string
    description: URL for Clearwater repository
    default: http://repo.cw-ngv.com/stable
  zone:
    type: string
    description: DNS zone
    default: example.com
  dn_range_start:
    type: string
    description: First directory number in pool
    default: "6505550000"
    constraints:
      - allowed_pattern: "[0-9]+"
        description: Must be numeric
  dn_range_length:
    type: string
    description: Number of directory numbers to add to pool
    default: "1000"
    constraints:
      - allowed_pattern: "[0-9]+"
        description: Must be numeric
  dns_mgmt_ip:
    type: string
    description: IP address for DNS server
  dnssec_key:
    type: string
    description: DNSSEC private key (Base64-encoded)
    constraints:
      - allowed_pattern: "[0-9A-Za-z+/=]+"
        description: Must be Base64-encoded
  etcd_ip:
    type: string
    description: IP address of an existing member of the etcd cluster
    default: ""
  index:
    type: number
    description: Index of this Ellis node in the Ellis cluster
    default: 0

resources:
  mgmt_port:
    type: OS::Neutron::Port
    properties:
      # Specify the network ID by string to work around OpenStack issues - see https://github.com/Metaswitch/clearwater-heat/issues/18.
      network_id: { str_replace: { params: { x: { get_param: private_mgmt_net_id } }, template: x } }
      security_groups:
        - { get_param: base_mgmt_security_group }
        - { get_param: ellis_mgmt_security_group }

  mgmt_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_mgmt_net_id }
      port_id: { get_resource: mgmt_port }

  server:
    type: OS::Nova::Server
    properties:
      name: { str_replace: { params: { __index__: { get_param: index }, __zone__: { get_param: zone } }, template: ellis-__index__.__zone__ } }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: mgmt_port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __repo_url__: { get_param: repo_url }
            __zone__: { get_param: zone }
            __public_mgmt_ip__: { get_attr: [ mgmt_floating_ip, floating_ip_address ] }
            __private_mgmt_ip__: { get_attr: [ mgmt_port, fixed_ips, 0, ip_address ] }
            __dn_range_start__: { get_param: dn_range_start }
            __dn_range_length__: { get_param: dn_range_length }
            __dns_mgmt_ip__: { get_param: dns_mgmt_ip }
            __dnssec_key__: { get_param: dnssec_key }
            __etcd_ip__ : { get_param: etcd_ip }
            __index__ : { get_param: index }
          template: |
            #!/bin/bash

            # Log all output to file.
            exec > >(tee -a /var/log/clearwater-heat-ellis.log) 2>&1
            set -x

            # Configure the APT software source.
            echo 'deb __repo_url__ binary/' > /etc/apt/sources.list.d/clearwater.list
            curl -L http://repo.cw-ngv.com/repo_key | apt-key add -
            apt-get update

            # Configure /etc/clearwater/local_config.  Add xdms_hostname here to use Homer's management
            # hostname instead of signaling.  This will override shared_config.  This works around
            # https://github.com/Metaswitch/ellis/issues/153.
            mkdir -p /etc/clearwater
            etcd_ip=__etcd_ip__
            [ -n "$etcd_ip" ] || etcd_ip=__private_mgmt_ip__
            cat > /etc/clearwater/local_config << EOF
            local_ip=__private_mgmt_ip__
            public_ip=__public_mgmt_ip__
            public_hostname=ellis-__index__.__zone__
            etcd_cluster=$etcd_ip
            xdms_hostname=homer-0.__zone__:7888
            EOF

            # Now install the software.
            DEBIAN_FRONTEND=noninteractive apt-get install ellis --yes --force-yes
            DEBIAN_FRONTEND=noninteractive apt-get install clearwater-management --yes --force-yes

            # Wait until etcd is up and running before uploading the shared_config
            /usr/share/clearwater/clearwater-etcd/scripts/wait_for_etcd

            # Configure and upload /etc/clearwater/shared_config.
            LOCAL_SHARED_CFG=$(/usr/share/clearwater/clearwater-config-manager/scripts/cw-config download shared_config --autoconfirm |sed 's/shared_config downloaded to //')
            cat > $LOCAL_SHARED_CFG << EOF
            # Deployment definitions
            home_domain=__zone__
            sprout_hostname=sprout.__zone__
            hs_hostname=hs.__zone__:8888
            hs_provisioning_hostname=hs-prov.__zone__:8889
            ralf_hostname=ralf.__zone__:10888
            xdms_hostname=homer.__zone__:7888
            sprout_impi_store=vellum.__zone__
            sprout_registration_store=vellum.__zone__
            homestead_impu_store=vellum.__zone__
            cassandra_hostname=vellum.__zone__
            chronos_hostname=vellum.__zone__
            ralf_session_store=vellum.__zone__

            upstream_port=0

            # Email server configuration
            smtp_smarthost=localhost
            smtp_username=username
            smtp_password=password
            email_recovery_sender=clearwater@example.org

            # Keys
            signup_key=secret
            turn_workaround=secret
            ellis_api_key=secret
            ellis_cookie_key=secret
            EOF
            /usr/share/clearwater/clearwater-config-manager/scripts/cw-config upload shared_config --autoconfirm

            # Allocate a pool of numbers to assign to users.  Before we do this,
            # restart clearwater-infrastructure to make sure that
            # local_settings.py runs to pick up the configuration changes.
            service clearwater-infrastructure restart
            service ellis stop
            /usr/share/clearwater/ellis/env/bin/python /usr/share/clearwater/ellis/src/metaswitch/ellis/tools/create_numbers.py --start __dn_range_start__ --count __dn_range_length__

            # Function to give DNS record type and IP address for specified IP address
            ip2rr() {
              if echo $1 | grep -q -e '[^0-9.]' ; then
                echo AAAA $1
              else
                echo A $1
              fi
            }

            # Update DNS
            retries=0
            while ! { nsupdate -y "__zone__:__dnssec_key__" -v << EOF
            server __dns_mgmt_ip__
            update add ellis-__index__.__zone__. 30 $(ip2rr __public_mgmt_ip__)
            update add ellis.__zone__. 30 $(ip2rr __public_mgmt_ip__)
            send
            EOF
            } && [ $retries -lt 10 ]
            do
              retries=$((retries + 1))
              echo 'nsupdate failed - retrying (retry '$retries')...'
              sleep 5
            done

            # Use the DNS server.
            echo 'nameserver __dns_mgmt_ip__' > /etc/dnsmasq.resolv.conf
            echo 'RESOLV_CONF=/etc/dnsmasq.resolv.conf' >> /etc/default/dnsmasq
            service dnsmasq force-reload

outputs:
  public_mgmt_ip:
    description: IP address in public management network
    value: { get_attr: [ mgmt_floating_ip, floating_ip_address ] }
  private_mgmt_ip:
    description: IP address in private management network
    value: { get_attr: [ mgmt_port, fixed_ips, 0, ip_address ] }
